### ISSUE TITLE
Forcing the use of ENV variables

### ISSUE THREAD

**Issue by justinlyman** [ankane/mainstreet#11]
It would be preferable to not use Environment variables for the SmartyStreets API keys, as this is not the Rails standard way of doing things.  It would be better to have a configuration class that can be used in an initializer, that way you can use environment variables or the built-in rails credentials management. I am happy to add this in a pull request if you are open to the change.

**Comment by ankane** [comment]
Hey @justinlyman, thanks for the suggestion. Users can configure SmartyStreets + Geocoder manually if they don't want to use environment variables, so I don't think anything additional is needed. See https://github.com/ankane/mainstreet/blob/959fbe2e712cc9daa4e5bab714d681c3ce685a27/lib/mainstreet.rb#L9
