### ISSUE TITLE
Disable Suite/Apartment Validation

### ISSUE THREAD

**Issue by brodyhoskins** [ankane/mainstreet#14]
I am using `validates_address` on a model, but when attempting to save it's blocked many times due to the suite/apartment validation failing. Because I am using this for shipping purposes this information isn't necessary and isn't available.

How can suite/apartment validation be bypassed so that models can be saved despite the verification failure?

**Comment by ankane** [comment]
Hey @brodyhoskins, there isn't a way to disable apartment confirmation right now, but happy to have an option for it if you'd like to add it.

**Comment by brodyhoskins** [comment]
I'd really like this option — I'm not sure where to begin to contribute adding it.

**Comment by ankane** [comment]
Check out the Contributing section of the readme for how to get set up. You can find the Ruby code in `lib`.
