### ISSUE TITLE
Allow dynamically passing in the Smarty Streets credentials to Geocoder

### ISSUE THREAD

**Issue by aleksandarpetrushev** [ankane/mainstreet#18]
I will attempt to submit a PR for this. I need to be able to use Geocoder with Smarty Streets for different Users (each User will use his own Smarty Streets account).

**Comment by ankane** [comment]
Hey @aleksandarpetrushev, we could probably add a `lookup` option to `AddressVerifier` and `validates_address` (similar to `country`) (and you could call `Geocode.configure` to add lookup services beforehand). Feel free to submit a PR.
