### ISSUE TITLE
Street2 force nil?

### ISSUE THREAD

**Issue by cbastable** [ankane/mainstreet#2]
Hi - apologies if I'm completely missing something here.

Is there a way to avoid the standardize_address method from forcing street2 to be nil?

I can always access it with original attributes -- but would be nice to be able to use street2 attribute itself.

Sorry again if I'm missing something obvious.

**Comment by ankane** [comment]
Hey @cbastable, you can try to set `street` and `street2` from the different components in `verification_info`. I'm not exactly sure how we'll this will work, which is why they are combined in the gem. Neither Google nor Smarty Streets return the street lines separately.

**Comment by ankane** [comment]
Cleaning up stale issues
