### ISSUE TITLE
Normalizing addresses

### ISSUE THREAD

**Issue by mdh** [ankane/mainstreet#22]
Hi Andrew,

Thanks for great gem! 

What do you think about "normalizing" addresses, e.g. capitizalization and exact phrasing? In other words replacing user input with results from Geocoder?

Shouldnt be too hard and I am willing to do it.

**Comment by ankane** [comment]
Hi @mdh, the gem originally did this, but it was removed in 0.2.0 as I'm not sure it was used much. The docs for manually adding it are [here](https://github.com/ankane/mainstreet/blob/v0.2.0/docs/0-2-Upgrade.md).
