### ISSUE TITLE
rails g mainstreet:address not working

### ISSUE THREAD

**Issue by bilalbash** [ankane/mainstreet#3]
following error wouldn't allow to generate migration:

Could not find geocoder-1.4.5 in any of the sources

i installed geocoder-1.4.5 but still same error comes up

**Comment by ankane** [comment]
Hey @bilalbash, be sure to run `bundle install` first.

**Comment by bilalbash** [comment]
couldn't able to produce this bug again as i re ran the bundle it worked now.
