### ISSUE TITLE
Only Run Validations if changes

### ISSUE THREAD

**Issue by johncjensen** [ankane/mainstreet#6]
Is there a validation I can add or you could add to this gem to where it limits api calls to SmartyStreets only if changes are detected to address fields within the model?

I am using the model with an associated join table for address inventory items and thus I'm updating address often but not making any changes to the address street/zip etc info.

**Comment by ankane** [comment]
Hey @johncjensen, this should already be the case. https://github.com/ankane/mainstreet/blob/91dd8bf9a281c95ea3d89c5746493e2ea58e6bbe/lib/mainstreet.rb#L25

**Comment by johncjensen** [comment]
Hey @ankane, I am using my address model a bit more advanced than probably the average.

My addresses are basically locations within a CRM for stores, where one account can have many addresses and addresses have many skus items through inventory_items.

Upon looking at the code you referenced, it does seem there is a validation inside the gem to check if address fields have changed, but upon looking at the API call count inside of SmartyStreets any time I touch/update an address object even if the fields aren't for example "street", "street2" "zip" etc it's bypassing that validation you referenced.

Any help would be immensely appreciated.

Wondering how I could specify the verify_address to only run if street/street2/zip/city/state are changed?

**Comment by ankane** [comment]
Hey @johncjensen, I'm not sure what it could be. I'd try cloning the project locally and trying to debug with your app. If you find that it is a Mainstreet bug, please reopen.
