### ISSUE TITLE
Get or Create

### ISSUE THREAD

**Issue by fameoflight** [ankane/mainstreet#7]
Right now address get the standardized and unique key is addresses_pkey 

but if try to insert new address which also resolves into same address there is no way to get the object without handling unique key error

Just wondering if you are open to this method on address model

@ankane

**Comment by ankane** [comment]
Hey @fameoflight, I don't think I understand. Can you explain more?

**Comment by fameoflight** [comment]
Sorry this was something on my end I messed up the sequence on table.

Closing this for now.
